### ISSUE TITLE
Scrollbar disappears in v 2.0.1

### ISSUE THREAD

**Issue by vonMitzscha** [Johann150/neutron#21]

**Comment by vonMitzscha** [comment]
In the new release 2.0.1 firstly the scrollbar does not work (sticks statically) and if the page extension is activated, the scrollbar simply disappears. Only the black area remains where the slider was once. 
There is no possibility to scroll!

**Comment by Johann150** [comment]
Can I assume that the page had already been extended, because otherwise it would be normal that the scrollbar cannot be moved?

**Comment by Johann150** [comment]
I assume that it happened after a few page extensions (probably around 7-10 times). The problem is probably the sizing of the scrollbar.

**Comment by Johann150** [comment]
It seems this issue is still not resolved. I just noticed it when trying it out on a real whiteboard. So the issue is again with the touch handlers being separate.

And the scrollbar disappearing is a mistake here, where it has to be adjusted to the new canvas sizing due to the scrollbar.
https://github.com/Johann150/neutron/blob/b545a86beb1d4ef235f9a9ff08c863badb75e555/draw.js#L130

**Comment by Johann150** [comment]
I checked it today with v2.0.3 on the real board and it seemed to work fine.
