### ISSUE TITLE
Pen icon doesn’t disappear 

### ISSUE THREAD

**Issue by vonMitzscha** [Johann150/neutron#25]
In previous electron builds, the pencil symbol always disappeared while writing. After the switch to the web version, the pen icon always remains visible, which firstly covers content and secondly can be very confusing when writing.

**Comment by Johann150** [comment]
Could you give a more precise description of when the cursor should not be shown, or rather when it should be shown?

**Comment by vonMitzscha** [comment]
Shown: Normally
Not be shown: Touch-Down (f.eg. during writing)

**Comment by Johann150** [comment]
I still think this is not a good solution. For example think about when a "stupid user" might be using Neutron on a computer with a mouse. They would probably think something went wrong because their cursor disappeared.

I would be ready to take the compromise to either
* a) switch to a cursor that is obstructing the view less or
* b) hide the cursor only when using touch inputs.

**Comment by vonMitzscha** [comment]
I think option b) would be the most practical solution.
